// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogClient interface {
	GetItemsFromDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response1, error)
	AddItemToWishlist(ctx context.Context, in *IdItem, opts ...grpc.CallOption) (*Response2, error)
}

type catalogClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogClient(cc grpc.ClientConnInterface) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) GetItemsFromDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response1, error) {
	out := new(Response1)
	err := c.cc.Invoke(ctx, "/service.Catalog/GetItemsFromDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) AddItemToWishlist(ctx context.Context, in *IdItem, opts ...grpc.CallOption) (*Response2, error) {
	out := new(Response2)
	err := c.cc.Invoke(ctx, "/service.Catalog/AddItemToWishlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServer is the server API for Catalog service.
// All implementations should embed UnimplementedCatalogServer
// for forward compatibility
type CatalogServer interface {
	GetItemsFromDB(context.Context, *Empty) (*Response1, error)
	AddItemToWishlist(context.Context, *IdItem) (*Response2, error)
}

// UnimplementedCatalogServer should be embedded to have forward compatible implementations.
type UnimplementedCatalogServer struct {
}

func (UnimplementedCatalogServer) GetItemsFromDB(context.Context, *Empty) (*Response1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemsFromDB not implemented")
}
func (UnimplementedCatalogServer) AddItemToWishlist(context.Context, *IdItem) (*Response2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItemToWishlist not implemented")
}

// UnsafeCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServer will
// result in compilation errors.
type UnsafeCatalogServer interface {
	mustEmbedUnimplementedCatalogServer()
}

func RegisterCatalogServer(s grpc.ServiceRegistrar, srv CatalogServer) {
	s.RegisterService(&Catalog_ServiceDesc, srv)
}

func _Catalog_GetItemsFromDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetItemsFromDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Catalog/GetItemsFromDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetItemsFromDB(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_AddItemToWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).AddItemToWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Catalog/AddItemToWishlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).AddItemToWishlist(ctx, req.(*IdItem))
	}
	return interceptor(ctx, in, info, handler)
}

// Catalog_ServiceDesc is the grpc.ServiceDesc for Catalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Catalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemsFromDB",
			Handler:    _Catalog_GetItemsFromDB_Handler,
		},
		{
			MethodName: "AddItemToWishlist",
			Handler:    _Catalog_AddItemToWishlist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CatalogService/proto/catalog.proto",
}
